### ISSUE TITLE
JPCSP not starting on OSX

### ISSUE THREAD

**Issue by saber00** [jpcsp/jpcsp#387]
When I open jpcsp, nothing comes up but application appears to be running according to docks. I have JRE8 installed.

**Comment by lightfirst** [comment]
Yet, It not runing.
I get this error:

-bash-3.2$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
-bash-3.2$ ./JavaApplicationStub
Exception in thread "GUI" java.lang.NullPointerException
	at jpcsp.MainGUI.<init>(MainGUI.java:237)
	at jpcsp.MainGUI$76.run(MainGUI.java:2904)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by gid15** [comment]
I don't really understand what is not running on OSX (I can't test it myself), but I've tried to avoid the above NullPointerException in e28be06.

**Comment by lightfirst** [comment]
@gid15 
Jpcsp can run now, but get another error when I try run UMD(except cube.iso cube.cso )

java.lang.OutOfMemoryError: Java heap space
	at org.objectweb.asm.ClassReader.readLabel(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at jpcsp.util.ClassAnalyzer.getParameters(ClassAnalyzer.java:64)
	at jpcsp.Allegrex.compiler.CompilerContext.logSyscall(CompilerContext.java:1212)
	at jpcsp.Allegrex.compiler.CompilerContext.visitSyscall(CompilerContext.java:1409)
	at jpcsp.Allegrex.compiler.CompilerContext.visitSyscall(CompilerContext.java:1567)
	at jpcsp.Allegrex.compiler.CompilerContext.compileSyscall(CompilerContext.java:2596)
	at jpcsp.Allegrex.Instructions$16.compile(Instructions.java:488)
	at jpcsp.Allegrex.compiler.CodeInstruction.compile(CodeInstruction.java:191)
	at jpcsp.Allegrex.compiler.CodeInstruction.compileDelaySlot(CodeInstruction.java:300)
	at jpcsp.Allegrex.compiler.CodeInstruction.compileDelaySlot(CodeInstruction.java:278)
	at jpcsp.Allegrex.compiler.CodeInstruction.compileJr(CodeInstruction.java:202)
	at jpcsp.Allegrex.compiler.CodeInstruction.compile(CodeInstruction.java:185)
	at jpcsp.Allegrex.compiler.CodeBlock.compile(CodeBlock.java:412)
	at jpcsp.Allegrex.compiler.CodeBlock.compile(CodeBlock.java:513)
	at jpcsp.Allegrex.compiler.CodeBlock.getExecutable(CodeBlock.java:556)
	at jpcsp.Allegrex.compiler.Compiler.analyse(Compiler.java:477)
	at jpcsp.Allegrex.compiler.Compiler.compile(Compiler.java:568)
	at jpcsp.Allegrex.compiler.Compiler.compile(Compiler.java:510)
	at jpcsp.Allegrex.compiler.CompilerClassLoader.findClass(CompilerClassLoader.java:50)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at _S1_2_883B268.s883b32c(_S1_2_883B268.java:248)
	at _S1_2_883B268.s(_S1_2_883B268.java:196)
	at _S1_2_8829F70.s(_S1_2_8829F70.java:52)
	at _S1_2_89BC0AC.s89bc128(_S1_2_89BC0AC.java:188)
	at _S1_2_89BC0AC.s(_S1_2_89BC0AC.java:124)
	at _S1_2_890B21C.s(_S1_2_890B21C.java:36)
	at _S1_2_8978240.s(_S1_2_8978240.java:64)
	at _S1_2_8978168.s8978168(_S1_2_8978168.java:112)
	at _S1_2_8978168.s(_S1_2_8978168.java:0)

**Comment by lightfirst** [comment]
Its ok debug using netbeans
how to create Jpcsp.app for MAC OS ?
![2015-06-08 12 29 34](https://cloud.githubusercontent.com/assets/4612168/8028375/add60d50-0dde-11e5-8206-c8302216abd9.png)

**Comment by gid15** [comment]
The MacOS is built using the "build-auto.xml" file: ant -f build-auto.xml dist-macosx
the additional Java VM parameters are missing in the current build (-Xmx1024m ...).
The file distsupport/macosx/Contents/Info.plist seems to be the place where to add these missing parameters, but I don't know the syntax to be used.

**Comment by lightfirst** [comment]
@gid15 Java Info.plist Key Reference for Mac
https://developer.apple.com/library/mac/documentation/Java/Reference/Java_InfoplistRef/Articles/JavaDictionaryInfo.plistKeys.html

**Comment by lightfirst** [comment]
I try add this, its woking.
<key>VMOptions</key>
<string>-Xmx1024m -Xss2m -XX:MaxPermSize=128m -XX:ReservedCodeCacheSize=64m </string>

**Comment by saber00** [comment]
@lightfirst sorry but I don't understand where to add "VMOptions -Xmx1024m -Xss2m -XX:MaxPermSize=128m -XX:ReservedCodeCacheSize=64m" to? 大神你英文太6看不懂。。

**Comment by lightfirst** [comment]
@saber00  Just download this one
下载这个就可以了
http://kuai.xunlei.com/d/TPqMBZdCKy94VQQA11c

**Comment by saber00** [comment]
@lightfirst 迅雷貌似下载不了，能上传到百度盘吗，谢了。

**Comment by lightfirst** [comment]
@saber00 http://pan.baidu.com/s/1i3gqwL3

**Comment by saber00** [comment]
Thanks

**Comment by gid15** [comment]
Update from lightfirst now included in bb9be06. Is this change sufficient?
Thank you for your help!

**Comment by saber00** [comment]
Hi, Thanks for the update, now the emulator can be opened but when I start a game, it is extremely slow and my fps is never higher than 10. Is this because JPCSP doesnt have enough memory?

**Comment by lightfirst** [comment]
@saber00  you need find a speed up settings.
设置一下模拟器就好。
![12](https://cloud.githubusercontent.com/assets/4612168/8373673/76db72f8-1c21-11e5-8a99-c83a3992fd76.PNG)

![13](https://cloud.githubusercontent.com/assets/4612168/8373678/8106951e-1c21-11e5-938f-4792d761623f.PNG)


另外问一下你电脑用的是什么型号的CPU和显卡，内存多大？

**Comment by saber00** [comment]
处理器： Intel core  i5-3210M
ＣＰＵ：２.５ＧＨＺ
ＲＡＭ：４Ｇ

**Comment by lightfirst** [comment]
最重要的显卡没说。

**Comment by saber00** [comment]
Intel HD Graphics 4000

**Comment by lightfirst** [comment]
没有独立显卡玩JPCSP会卡

**Comment by saber00** [comment]
看来玩不了高达多人模式了QAQ

**Comment by lightfirst** [comment]
@saber00 
除非联机，高达你还是用PPSSPP模拟器玩吧

**Comment by dogo** [comment]
I'm not able to run too. 

Running using eclipse:

java version "1.7.0_80"

VM args
-Xmx1024m -Xss2m -XX:MaxPermSize=128m -XX:ReservedCodeCacheSize=64m -Djava.library.path=lib/macosx

Main class
jpcsp.MainGUI

Eclipse log
```
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
java.lang.RuntimeException: Jpcsp cannot display.
The cause could be that you are using an old graphic card driver (try to update it)
or your display format is not compatible with Jpcsp (try to change your display format, Jpcsp requires 32 bit color depth)
or the anti-aliasing settings is not supported by your display (leave the Jpcsp anti-aliasing to its default setting)
	at jpcsp.HLE.modules150.sceDisplay.start(sceDisplay.java:989)
	at jpcsp.HLE.modules.HLEModuleManager.startModules(HLEModuleManager.java:415)
	at jpcsp.Emulator.initCpu(Emulator.java:201)
	at jpcsp.Emulator.load(Emulator.java:170)
	at jpcsp.Emulator.load(Emulator.java:153)
	at jpcsp.MainGUI.loadFile(MainGUI.java:1543)
	at jpcsp.MainGUI.loadUMD(MainGUI.java:1908)
	at jpcsp.GUI.UmdBrowser.loadSelectedfile(UmdBrowser.java:728)
	at jpcsp.GUI.UmdBrowser.loadButtonActionPerformed(UmdBrowser.java:1046)
	at jpcsp.GUI.UmdBrowser.access$22(UmdBrowser.java:1045)
	at jpcsp.GUI.UmdBrowser$6.actionPerformed(UmdBrowser.java:922)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at java.awt.Component.show(Component.java:1655)
	at java.awt.Component.setVisible(Component.java:1607)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at jpcsp.MainGUI.openUmdActionPerformed(MainGUI.java:1774)
	at jpcsp.MainGUI.access$7(MainGUI.java:1761)
	at jpcsp.MainGUI$7.actionPerformed(MainGUI.java:463)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by dogo** [comment]
hum, It's something related to an old version of LWJGL, I made a manual update to LWJGL 2.9.3 and everything seems fine

![ucjs10041-shot-2](https://cloud.githubusercontent.com/assets/1487375/9854731/aaf0d666-5ae0-11e5-8d96-599f40893a24.png)
