### ISSUE TITLE
UMD VIDEO issue

### ISSUE THREAD

**Issue by lightfirst** [jpcsp/jpcsp#388]
![bandicam 2015-06-15 10-02-19-043](https://cloud.githubusercontent.com/assets/4612168/8151915/cea7b4ce-1348-11e5-9a4b-d110a436b784.jpg)
1.  2x video size not work
2.  not sound (just like pmf, mps video also using atrat3+ audio)
3.  not support UMD Menu, TRACK LIST, etc 

PSP
![img_20150615_103340](https://cloud.githubusercontent.com/assets/4612168/8152196/b6e771a4-134c-11e5-9bd0-876fff1c3af4.jpg)

![img_20150615_103353](https://cloud.githubusercontent.com/assets/4612168/8152207/d8de0692-134c-11e5-952e-5b5a3e54c609.jpg)

JPCSP
![bandicam 2015-06-15 10-41-31-241](https://cloud.githubusercontent.com/assets/4612168/8152221/f89a5738-134c-11e5-9266-17f6cbf5b259.jpg)

![bandicam 2015-06-15 10-42-17-802](https://cloud.githubusercontent.com/assets/4612168/8152225/0ecd42f4-134d-11e5-8257-3c391d66c27c.jpg)

**Comment by lightfirst** [comment]
TEST with f187aa
have sound, but still have may bug. 
00001.MPS, the biggest video (1.6G) also decode a few second then skip


00:12:12 ERROR     h264 - UMD Video Player Thread - H264Decoder.decode
java.lang.ArrayIndexOutOfBoundsException
00:12:12  INFO videoplayer - UMD Video Player Thread - Loading stream: UMD_VIDEO/STREAM/00098.MPS
00:12:12  INFO videoplayer - UMD Video Player Thread - Found CLIPINF data for this stream: UMD_VIDEO/CLIPINF/00098.CLP
00:12:22  INFO videoplayer - GUI - Loading stream: UMD_VIDEO/STREAM/00001.MPS
00:12:22  INFO videoplayer - GUI - Found CLIPINF data for this stream: UMD_VIDEO/CLIPINF/00001.CLP
00:12:41 ERROR     h264 - UMD Video Player Thread - H264Decoder.decode
java.lang.ArrayIndexOutOfBoundsException
00:12:41  INFO videoplayer - UMD Video Player Thread - Loading stream: UMD_VIDEO/STREAM/00098.MPS
00:12:41  INFO videoplayer - UMD Video Player Thread - Found CLIPINF data for this stream: UMD_VIDEO/CLIPINF/00098.CLP

**Comment by lightfirst** [comment]
![2](https://cloud.githubusercontent.com/assets/4612168/9091182/4872efc0-3bd1-11e5-9648-d6d624c7f9a9.PNG)

**Comment by gid15** [comment]
The video is currently displayed in its native size, which is larger than the PSP display. I'm first focusing on the correct decoding and will address the resizing later...

**Comment by lightfirst** [comment]
get new log from jpcsp c65f137

21:26:49  INFO videoplayer - UMD Video Player Thread - Loading stream: UMD_VIDEO/STREAM/00002.MPS
21:26:49  INFO videoplayer - UMD Video Player Thread - Found CLIPINF data for this stream: UMD_VIDEO/CLIPINF/00002.CLP
21:26:51 ERROR     h264 - UMD Video Player Thread - H264Decoder.decode
java.lang.ArrayIndexOutOfBoundsException: 2333
	at com.twilight.h264.decoder.H264DSPContext.idct_internal(H264DSPContext.java:417)
	at com.twilight.h264.decoder.H264DSPContext.h264_idct_add16(H264DSPContext.java:541)
	at com.twilight.h264.decoder.H264Context.hl_decode_mb_internal(H264Context.java:2523)
	at com.twilight.h264.decoder.H264Context.ff_h264_hl_decode_mb(H264Context.java:2578)
	at com.twilight.h264.decoder.H264Context.decode_slice(H264Context.java:4916)
	at com.twilight.h264.decoder.H264Context.decode_nal_units(H264Context.java:6615)
	at com.twilight.h264.decoder.H264Context.decode_frame(H264Context.java:8594)
	at com.twilight.h264.decoder.H264Decoder.decode(H264Decoder.java:35)
	at com.twilight.h264.decoder.MpegEncContext.avcodec_decode_video2(MpegEncContext.java:2300)
	at jpcsp.media.codec.h264.H264Decoder.decode(H264Decoder.java:69)
	at jpcsp.GUI.UmdVideoPlayer.stepVideo(UmdVideoPlayer.java:840)
	at jpcsp.GUI.UmdVideoPlayer$MpsDisplayThread.run(UmdVideoPlayer.java:973)
21:26:51  INFO videoplayer - UMD Video Player Thread - Loading stream: UMD_VIDEO/STREAM/00001.MPS
21:26:51  INFO videoplayer - UMD Video Player Thread - Found CLIPINF data for this stream: UMD_VIDEO/CLIPINF/00001.CLP

**Comment by lightfirst** [comment]
VIDEO INFO:

General
Complete name                  : F:\jpcsp\jpcsp-windows-x86-amd64\00001.MPS
Format                         : MPEG-PS
File size                      : 1.61 GiB
Duration                       : 1h 58mn
Overall bit rate mode          : Variable
Overall bit rate               : 1 947 Kbps

Video
ID                             : 224 (0xE0)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L3.0
Format settings, CABAC         : Yes
Format settings, ReFrames      : 2 frames
Duration                       : 1h 58mn
Bit rate mode                  : Variable
Bit rate                       : 1 908 Kbps
Width                          : 720 pixels
Height                         : 480 pixels
Display aspect ratio           : 16:9
Frame rate                     : 29.970 fps
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Interlaced
Bits/(Pixel*Frame)             : 0.184
Stream size                    : 1.58 GiB (98%)
Color primaries                : BT.601 NTSC
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601

Text
ID                             : 189 (0xBD)
Format                         : RLE
Format/Info                    : Run-length encoding
Duration                       : 1h 58mn
Delay relative to video        : -50ms

**Comment by gid15** [comment]
I've fixed a few porting issues in h264j (the java video decoder). Could you retest?

**Comment by lightfirst** [comment]
video decode success, but have scan line 
![jpcsp-umdvideo](https://cloud.githubusercontent.com/assets/4612168/9406979/dabce292-4837-11e5-9b4b-35eb2c501fb1.jpg)

**Comment by lightfirst** [comment]
![img_20160414_233053](https://cloud.githubusercontent.com/assets/4612168/14535508/d2d663cc-02a0-11e6-80c6-3cbf068e820a.jpg)

**Comment by lightfirst** [comment]
What JPCSP  missing is  telecontroller, for now, Jpcsp is a mps players, only play the mps on ISO.

**Comment by lightfirst** [comment]
UMD VIDEO Final Fantasy VII: Advent Children
probably
video looks not good:
![bandicam 2016-04-15 01-19-04-871](https://cloud.githubusercontent.com/assets/4612168/14537092/1ed9c884-02a8-11e6-9027-03abffc96cae.jpg)
