### ISSUE TITLE
Runnung jpcsp on linux

### ISSUE THREAD

**Issue by latot** [jpcsp/jpcsp#402]
Hi, i'm new in this so probably i can skip some info...

well, i can't run jpcsp this is the log:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:82)
	at org.lwjgl.Sys.<clinit>(Sys.java:99)
	at org.lwjgl.opengl.AWTGLCanvas.<clinit>(AWTGLCanvas.java:85)
	at jpcsp.HLE.modules.sceDisplay.<init>(sceDisplay.java:771)
	at jpcsp.HLE.Modules.<clinit>(Modules.java:205)
	at jpcsp.crypto.AES128.<clinit>(AES128.java:37)
	at jpcsp.MainGUI.main(MainGUI.java:2879)
```

steps i follow to run it:

open project NB.
change java to the system (i use jdk 1.7)
build it (don't get any error)
in a terminal run ./start-linux-amd64.sh
error message

i'm using gentoo 64

Thx.

**Comment by lightfirst** [comment]
working fine for me. I am using ubuntu 64bit. 
in terminal I run sh start-linux-amd64.sh

**Comment by latot** [comment]
full build log:

```
ant -f /home/pipe/Documentos/git/jpcsp -Dnb.internal.action.name=build jar
init:
deps-jar:
Created dir: /home/pipe/Documentos/git/jpcsp/build
Updating property file: /home/pipe/Documentos/git/jpcsp/build/built-jar.properties
Created dir: /home/pipe/Documentos/git/jpcsp/build/classes
Created dir: /home/pipe/Documentos/git/jpcsp/build/empty
Created dir: /home/pipe/Documentos/git/jpcsp/build/generated-sources/ap-source-output
Compiling 854 source files to /home/pipe/Documentos/git/jpcsp/build/classes
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/DisassemblerModule/DisassemblerFrame.java:113: warning: [unchecked] unchecked call to setPrototypeCellValue(E) as a member of the raw type JList
        disasmList.setPrototypeCellValue("PROTOTYPE");
  where E is a type-variable:
    E extends Object declared in class JList
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/DisassemblerModule/DisassemblerFrame.java:162: warning: [unchecked] unchecked call to setCellRenderer(ListCellRenderer<? super E>) as a member of the raw type JList
        disasmList.setCellRenderer(new StyledListCellRenderer() {
  where E is a type-variable:
    E extends Object declared in class JList
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/DisassemblerModule/DisassemblerFrame.java:324: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
                    listmodel.addElement(line);
  where E is a type-variable:
    E extends Object declared in class DefaultListModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/DisassemblerModule/DisassemblerFrame.java:332: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
                    listmodel.addElement(String.format("   %08x: invalid address", pc));
  where E is a type-variable:
    E extends Object declared in class DefaultListModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/MemoryBreakpoints/MemoryBreakpointsDialog.java:65: warning: [unchecked] unchecked call to addItem(E) as a member of the raw type JComboBox
        combo.addItem("READ");
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/MemoryBreakpoints/MemoryBreakpointsDialog.java:66: warning: [unchecked] unchecked call to addItem(E) as a member of the raw type JComboBox
        combo.addItem("WRITE");
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/MemoryBreakpoints/MemoryBreakpointsDialog.java:67: warning: [unchecked] unchecked call to addItem(E) as a member of the raw type JComboBox
        combo.addItem("READWRITE");
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/DisassemblerModule/ViewTooltips.java:198: warning: [unchecked] unchecked call to getListCellRendererComponent(JList<? extends E>,E,int,boolean,boolean) as a member of the raw type ListCellRenderer
                ren.getListCellRendererComponent(list,
  where E is a type-variable:
    E extends Object declared in interface ListCellRenderer
/home/pipe/Documentos/git/jpcsp/src/jpcsp/Debugger/DisassemblerModule/ViewTooltips.java:504: warning: [unchecked] unchecked call to getListCellRendererComponent(JList<? extends E>,E,int,boolean,boolean) as a member of the raw type ListCellRenderer
            renderer = list.getCellRenderer().getListCellRendererComponent(list, nd, row, sel, false);
  where E is a type-variable:
    E extends Object declared in interface ListCellRenderer
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/ControlsGUI.java:421: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type MutableComboBoxModel
            comboBox.addElement(c);
  where E is a type-variable:
    E extends Object declared in interface MutableComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/ControlsGUI.java:471: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        controllerBox.setModel(makeControllerComboBoxModel());
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:141: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
        dlm.addElement(settings.readString("emu.umdpath"));
  where E is a type-variable:
    E extends Object declared in class DefaultListModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:150: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
                dlm.addElement(umdPath);
  where E is a type-variable:
    E extends Object declared in class DefaultListModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:323: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type MutableComboBoxModel
            comboBox.addElement(item);
  where E is a type-variable:
    E extends Object declared in interface MutableComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:392: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type MutableComboBoxModel
        comboBox.addElement("Native");
  where E is a type-variable:
    E extends Object declared in interface MutableComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:402: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type MutableComboBoxModel
                    comboBox.addElement(resolution);
  where E is a type-variable:
    E extends Object declared in interface MutableComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:571: warning: [unchecked] unchecked call to setModel(ListModel<E>) as a member of the raw type JList
        lbUMDPaths.setModel(new DefaultListModel());
  where E is a type-variable:
    E extends Object declared in class JList
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:594: warning: [unchecked] unchecked call to DefaultComboBoxModel(E[]) as a member of the raw type DefaultComboBoxModel
        modelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PSP-1000", "PSP-2000", "PSP-3000", "PSP-3000 (V2)", "PSP-N1000 (GO)" }));
  where E is a type-variable:
    E extends Object declared in class DefaultComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:594: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        modelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PSP-1000", "PSP-2000", "PSP-3000", "PSP-3000 (V2)", "PSP-N1000 (GO)" }));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:697: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        languageBox.setModel(makeComboBoxModel(getImposeLanguages()));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:703: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        buttonBox.setModel(makeComboBoxModel(getImposeButtons()));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:751: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        daylightBox.setModel(makeComboBoxModel(getSysparamDaylightSavings()));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:757: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        timeFormatBox.setModel(makeComboBoxModel(getSysparamTimeFormats()));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:763: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        dateFormatBox.setModel(makeComboBoxModel(getSysparamDateFormats()));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:769: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        wlanPowerBox.setModel(makeComboBoxModel(getSysparamWlanPowerSaves()));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:775: warning: [unchecked] unchecked call to DefaultComboBoxModel(E[]) as a member of the raw type DefaultComboBoxModel
        adhocChannelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "1", "6", "11" }));
  where E is a type-variable:
    E extends Object declared in class DefaultComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:775: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        adhocChannelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "1", "6", "11" }));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:996: warning: [unchecked] unchecked call to DefaultComboBoxModel(E[]) as a member of the raw type DefaultComboBoxModel
        methodMaxInstructionsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "500", "1000", "3000" }));
  where E is a type-variable:
    E extends Object declared in class DefaultComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:996: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        methodMaxInstructionsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "500", "1000", "3000" }));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:1035: warning: [unchecked] unchecked call to DefaultComboBoxModel(E[]) as a member of the raw type DefaultComboBoxModel
        antiAliasingBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "x4", "x8", "x16" }));
  where E is a type-variable:
    E extends Object declared in class DefaultComboBoxModel
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:1035: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        antiAliasingBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "x4", "x8", "x16" }));
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:1039: warning: [unchecked] unchecked call to setModel(ComboBoxModel<E>) as a member of the raw type JComboBox
        resolutionBox.setModel(makeResolutions());
  where E is a type-variable:
    E extends Object declared in class JComboBox
/home/pipe/Documentos/git/jpcsp/src/jpcsp/GUI/SettingsGUI.java:1324: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
            dlm.addElement(pathtoadd.getPath());
  where E is a type-variable:
    E extends Object declared in class DefaultListModel
33 warnings
Copying 67 files to /home/pipe/Documentos/git/jpcsp/build/classes
compile:
Created dir: /home/pipe/Documentos/git/jpcsp/bin
Copying 1 file to /home/pipe/Documentos/git/jpcsp/build
Copy libraries to /home/pipe/Documentos/git/jpcsp/bin/lib.
Building jar: /home/pipe/Documentos/git/jpcsp/bin/jpcsp.jar
To run this application from the command line without Ant, try:
java -jar "/home/pipe/Documentos/git/jpcsp/bin/jpcsp.jar"
jar:
BUILD SUCCESSFUL (total time: 12 seconds)
```

**Comment by latot** [comment]
i really don't know why don't works, the lwjgl are in the libs in nb...

**Comment by lightfirst** [comment]
You can try download JPCSP from Automatic jpcsp builds http://www.emunewz.net/forum/forumdisplay.php?fid=204

**Comment by latot** [comment]
yes, but the idea its can build it D:

**Comment by latot** [comment]
mm, seems was a nb problem, with a update now works (but i can't be sure of the origin of the problem)
Thx All.
