### ISSUE TITLE
Jpcsp opening, and appearing to be running, but nothing popping up.

### ISSUE THREAD

**Issue by CrazyPenguin1964** [jpcsp/jpcsp#411]
When I open it by running it in Terminal, it gives me this:

Exception in thread "GUI" java.lang.NullPointerException
	at jpcsp.MainGUI.<init>(MainGUI.java:237)
	at jpcsp.MainGUI$76.run(MainGUI.java:2904)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

There was an earlier thread with this problem, but it appeared to have been solved in a more recent update? I'm using the latest version of Jpscp, and still having this problem. I'm running Mac OS 10.9 and have the latest version of Java. Any help appreciated!

**Comment by teresgezer** [comment]
Mine is the same
