### ISSUE TITLE
 InputStream cannot be null 

### ISSUE THREAD

**Issue by mrcmunir** [jpcsp/jpcsp#441]
```
Exception in thread "main" java.lang.IllegalArgumentException: InputStream cannot be null
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:117)
	at jpcsp.crypto.PreDecrypt.init(PreDecrypt.java:149)
	at jpcsp.MainGUI.main(MainGUI.java:3023)
```
 broken by commit 9cc0d6ac12da474bc907818a04449bdff8f2bc27
Any ideas? .

**Comment by gid15** [comment]
Where have you the build from? It seems the file jpcsp/crypto/PreDecrypt.xml is missing in that build.
