### ISSUE TITLE
UMD Video Games cannot play.

### ISSUE THREAD

**Issue by vin7t123** [jpcsp/jpcsp#445]
Some UMD Video Games just got stuck at title page, with an Error Message:
```text
Running Jpcsp 64bit...
Exception in thread "UMD Video Player Thread" java.util.EmptyStackException
        at java.util.Stack.peek(Stack.java:102)
        at java.util.Stack.pop(Stack.java:84)
        at jpcsp.format.rco.vsmx.interpreter.VSMXInterpreter.interpret(VSMXInterpreter.java:112)
        at jpcsp.format.rco.vsmx.interpreter.VSMXInterpreter.interpret(VSMXInterpreter.java:617)
        at jpcsp.format.rco.vsmx.interpreter.VSMXInterpreter.interpretFunction(VSMXInterpreter.java:678)
        at jpcsp.format.rco.vsmx.objects.MoviePlayer.onChapter(MoviePlayer.java:205)
        at jpcsp.GUI.UmdVideoPlayer.stepVideo(UmdVideoPlayer.java:1269)
        at jpcsp.GUI.UmdVideoPlayer$MpsDisplayThread.run(UmdVideoPlayer.java:1368)
```

## Game info:
Nugase! Yakyuuken Polorigurabia Tengoku (UMD-Video) (Japan Version)

>Note. Other UMD Video games also failed. e.g:
IDOL JANKENInteractiveUMD Movie

**Comment by vin7t123** [comment]
@gid15 Pls help, thanks.

**Comment by gid15** [comment]
Yes, there is still a lot to discover on the format and special programming language used in UMD Videos.

Please post a log file at the TRACE level, that might help making some progress. But do not expect a functional version any time soon as there is still a lot to discover...

**Comment by vin7t123** [comment]
Thanks for your quick reply. Here is my TRACE log when it reproduced.

[log20181215_for_umdVideoGame.txt](https://github.com/jpcsp/jpcsp/files/2682608/log20181215_for_umdVideoGame.txt)

**Comment by vin7t123** [comment]
Add another related `UMD Video Game`'s error log in case you need more:
![lovex2kiss_error](https://user-images.githubusercontent.com/16187748/50043104-69710b80-00a9-11e9-8ee0-b91202a64012.png)

[log20181215_for_LOVEx2KISS.txt](https://github.com/jpcsp/jpcsp/files/2682613/log20181215_for_LOVEx2KISS.txt)
Thanks.

**Comment by vin7t123** [comment]
Thank you for fixing it. I want to try see if it works now, but no recent build found, could you trigger a dev build for this? Or should I build it by myself?

**Comment by ngeojiajun** [comment]
@gid15 seem no impact as i also get same error. By the way, is it any reliable way to dump the vsmx code so we can examine the code?

**Comment by gid15** [comment]
You can see the VSMX code when setting the log level to TRACE, see as an example one of the log files posted above.

**Comment by KoleckOLP** [comment]
Was there any progress on this since last comment?

**Comment by gid15** [comment]
@KoleckOLP If you have another test case, please post a log file at TRACE level. Thank you!

**Comment by KoleckOLP** [comment]
I have a few interactive UMD Video iso's, I will post logs if I figure out how to get them.

**Comment by KoleckOLP** [comment]
So I have tried Playing the Silent Hill video UMD, it plays but does not look properly, the menu of the movie is bugged on screen while the movie plays.
![image](https://user-images.githubusercontent.com/22729896/149168595-5b449da6-4b0a-408c-852e-0d61e7d0eb8f.png)

I have tried Silent Hill the Experience interactive UMD and it to my surprise worked better, I was able to navigate and play videos, the videos look blocky at fast motion. And the audio is buggy. (but worked the best)

And than I tried this lewd~ish rock paper scissors game on video UMD and it does not even get to the menu it start playing video seemingly at random. The audio is not in sync with the video and you can't even get to the rock paper scissors.

The UI of the whole emulator is incredibly buggy, I have only tried video UMD because I am interested in those.

the log files are really big so I can't paste them here or pastebin so I uploaded them to onedrive/sharepoint

https://fosfacz-my.sharepoint.com/:f:/g/personal/kurz_fosfa_cz/Ev7xLiOxXB1Hq_rDkzEetOgBTAZ5duRvEEKUygrunDjhuw?e=TbOGT9

I can provide the ISO's for devs to test if they are interested.
