### ISSUE TITLE
JPCSP fails to boot in LLE mode on Linux

### ISSUE THREAD

**Issue by JesusXD88** [jpcsp/jpcsp#478]
JPCSP boots fine the firmware installer and the firmware update (6.61) installs fine. However, when it enters reboot mode (either by booting after firmware installation or manually by passing the command line parameter --reboot) the execution halts, throwing the below error. I've tried the latest version published on Emunewz, some older versions and even building JPCSP from latest commit by myself (thanks for the building guide recently published on the readme!).
The distro is Arch Linux x64 using 5.14.16-zen1-1-zen Linux Kernel. The JPCSP video settings are all disabled except video rendering, which is set to External software rendering. The two first entries in memory section are enabled as well.
I can confirm this issue doesn't happen on Windows (with the same settings checked as on Linux) using latest version published on Emunewz. Here is also attached the log.txt.
```
┌─[jesusxd88@JXArch] - [~/jpcsp] - [6942]
└─[$] bash start-linux-amd64.sh --reboot                             [17:30:48]
nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event16): Failed to open device /dev/input/event16 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event17): Failed to open device /dev/input/event17 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event18): Failed to open device /dev/input/event18 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event19): Failed to open device /dev/input/event19 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event20): Failed to open device /dev/input/event20 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event21): Failed to open device /dev/input/event21 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event22): Failed to open device /dev/input/event22 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event23): Failed to open device /dev/input/event23 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)

nov 19, 2021 5:30:54 PM net.java.games.input.ControllerEnvironment log
INFORMACIÓN: Linux plugin claims to have found 1 controllers
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr
java.lang.RuntimeException: Cannot find executable
	at jpcsp.Allegrex.compiler.RuntimeContext.jumpCall(RuntimeContext.java:162)
	at jpcsp.Allegrex.compiler.RuntimeContext.jump(RuntimeContext.java:212)
	at _S1_3_0x88602900.s(_S1_3_0x88602900.java:524)
	at _S1_3_0x88602758.s(_S1_3_0x88602758.java:348)
	at _S1_3_0x88602758.exec(_S1_3_0x88602758.java)
	at jpcsp.Allegrex.compiler.RuntimeContext.jumpCall(RuntimeContext.java:180)
	at jpcsp.Allegrex.compiler.RuntimeContext.jump(RuntimeContext.java:212)
	at _S1_3_0x04000280.s(_S1_3_0x04000280.java:504)
	at _S1_3_0x04000000.s(_S1_3_0x04000000.java:1476)
	at _S1_3_0x04000000.exec(_S1_3_0x04000000.java)
	at jpcsp.Allegrex.compiler.RuntimeContext.jumpCall(RuntimeContext.java:180)
	at jpcsp.Allegrex.compiler.RuntimeContext.jump(RuntimeContext.java:212)
	at jpcsp.Allegrex.compiler.RuntimeContext.execWithReturnAddress(RuntimeContext.java:867)
	at jpcsp.Allegrex.compiler.RuntimeContext.runThread(RuntimeContext.java:949)
	at jpcsp.Allegrex.compiler.RuntimeThread.run(RuntimeThread.java:50)
```
[log.txt.zip](https://github.com/jpcsp/jpcsp/files/7573033/log.txt.zip)

**Comment by gid15** [comment]
Good catch, I had never tried that scenario on a Linux. Does it now work with the revision eb74865?

**Comment by JesusXD88** [comment]
Now is working very fine on the latest commit. Thank you so much!
![Screenshot_20211121_170153](https://user-images.githubusercontent.com/71974251/142769425-40d477a3-6c09-402a-b180-22dc852ee082.png)

**Comment by gid15** [comment]
Great!
