### ISSUE TITLE
Tom Clancy's Ghost Recon - Predator (USA) crashes out on name input

### ISSUE THREAD

**Issue by benderscruffy** [jpcsp/jpcsp#505]
[log.zip](https://github.com/jpcsp/jpcsp/files/10199567/log.zip)
16:56:04 ERROR  runtime - user_main - Catched Throwable in RuntimeThread:
java.lang.NullPointerException
	at jpcsp.HLE.modules.sceUtility$OskUtilityDialogState.executeUpdateVisible(sceUtility.java:2038)
	at jpcsp.HLE.modules.sceUtility$UtilityDialogState.executeUpdate(sceUtility.java:875)
	at jpcsp.HLE.modules.sceUtility.sceUtilityOskUpdate(sceUtility.java:4812)
	at _S1_2_0x08BB493C.s(_S1_2_0x08BB493C.java:4)
	at _S1_2_0x088097D4.s(_S1_2_0x088097D4.java:72)
	at _S1_2_0x088E6010.s88e6d7c(_S1_2_0x088E6010.java:3528)
	at _S1_2_0x088E6010.s(_S1_2_0x088E6010.java:3436)
	at _S1_2_0x088E6010.exec(_S1_2_0x088E6010.java)
	at jpcsp.Allegrex.compiler.RuntimeContext.jumpCall(RuntimeContext.java:181)
	at jpcsp.Allegrex.compiler.RuntimeContext.jump(RuntimeContext.java:213)
	at jpcsp.Allegrex.compiler.RuntimeContext.execWithReturnAddress(RuntimeContext.java:868)
	at jpcsp.Allegrex.compiler.RuntimeContext.runThread(RuntimeContext.java:950)
	at jpcsp.Allegrex.compiler.RuntimeThread.run(RuntimeThread.java:50)
16:56:14  INFO hle.ThreadManForUser - GUI - ----------------------------- ThreadMan exit -----------------------------

**Comment by gid15** [comment]
Thank you for reporting!

Is it now fixed with the latest commit cf0cecd?
