### ISSUE TITLE
Java error in start-windows-x86.bat

### ISSUE THREAD

**Issue by AppTesterMC** [jpcsp/jpcsp#528]
# Context error
I tried to run the release "XLink Kai Support 1.0" downloaded from this repository, on my machine running `Microsoft Windows [Version 10.0.19045.4046]` and the java version:
```
java 14 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```

# Reproduce the error
The command `start-windows-x86.bat` failed with the following error.

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: jpcsp/MainGUI : Unsupported major.minor version 52.0
         at java.lang.ClassLoader.defineClass1(Native Method)
         at java.lang.ClassLoader.defineClass(Unknown Source)
         at java.security.SecureClassLoader.defineClass(Unknown Source)
         at java.net.URLClassLoader.defineClass(Unknown Source)
         at java.net.URLClassLoader.access$100(Unknown Source)
         at java.net.URLClassLoader$1.run(Unknown Source)
         at java.net.URLClassLoader$1.run(Unknown Source)
         at java.security.AccessController.doPrivileged(Native Method)
         at java.net.URLClassLoader.findClass(Unknown Source)
         at java.lang.ClassLoader.loadClass(Unknown Source)
         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
         at java.lang.ClassLoader.loadClass(Unknown Source)
         at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

# Solution
The solution was to «force» the command `set JAVA_CMD=java.exe` line 16 of `start-windows-x86.bat`
```Batchfile
...
:JAVA
REM set JAVA_CMD=%ProgramFiles%\Java\jre7\bin\java.exe
if not exist "%JAVA_CMD%" set JAVA_CMD=java.exe
GOTO RUN
...
```

**Comment by AppTesterMC** [comment]
Wrongly run x86 instead of amd64.
