### ISSUE TITLE
HELP! The emulator doesnt WANT to LAUNCH!

### ISSUE THREAD

**Issue by Team240Games-BarOS** [jpcsp/jpcsp#529]
The EMULATOR brings Running Jpcsp 64bit...
Exception in thread "GUI" java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x76424095) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x76424095
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
        at jpcsp.MainGUI.initJide(MainGUI.java:285)
        at jpcsp.MainGUI.<init>(MainGUI.java:205)
        at jpcsp.MainGUI$76.run(MainGUI.java:3152)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90). HELP ,MEEEEEEEEEEEEEEEEEE!!!

**Comment by diamant3** [comment]
Could you use this https://adoptium.net/temurin/releases/ instead of your current installed JDK?

**Comment by Team240Games-BarOS** [comment]
> You should use this https://adoptium.net/temurin/releases/ instead of your current installed JDK

It doesnt work. it still brings up the issue :(

**Comment by diamant3** [comment]
okay, could you show me how to reproduce this issue like what OS and java version you use?

**Comment by Team240Games-BarOS** [comment]
> okay, could you show me how to reproduce this issue like what OS and java version you use?

Version 8, Windows 10

How to reproduce: Download V8. and launch JPCSP.

**Comment by diamant3** [comment]
Thanks. Okay, use the latest JDK https://adoptium.net/temurin/releases/ for now

**Comment by Team240Games-BarOS** [comment]
Anyways. going off topic. why does Pac-Man look weird on Namco Museum Battle Collection? Is it a emulator fault?
